apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: db
build:
  artifacts:
    - image: db-app.dev
      context: .
      sync:
        manual:
          - src: backend/db-app/src/**/*
            dest: /usr/src
          - src: backend/lib-api/src/**/*
            dest: /usr/src
          - src: backend/lib-types/src/**/*'
            dest: /usr/src
          - src: backend/target/aarch64-unknown-linux-gnu/debug/db-app*
            dest: /usr/src
          - src: backend/target/aarch64-unknown-linux-gnu/debug/libdb_app.*
            dest: /usr/src
      docker:
        dockerfile: backend/db-app/Dockerfile
        target: dev
  local:
    push: false
    useBuildkit: true
manifests:
  rawYaml:
    - tools/k8s/dev/db/*.yaml
    - tools/k8s/dev/crowdtrust-api/db-app*.yaml
deploy:
  kubectl: {}
  kubeContext: docker-desktop
portForward:
  - resourceType: service
    resourceName: postgresql
    port: 5432
