apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: blockchain
build:
  artifacts:
    - image: blockchain-dev
      context: .
      sync:
        manual:
          - src: contracts/lib/**/*
            dest: /anvil
          - src: contracts/script/**/*
            dest: /anvil
          - src: contracts/src/**/*
            dest: /anvil
          - src: backend/blockchain-dev/start-chain.bash
            dest: /anvil
      docker:
        dockerfile: backend/blockchain-dev/Dockerfile
  local:
    push: false
    useBuildkit: true
manifests:
  rawYaml:
    - tools/k8s/dev/blockchain-dev/*.yaml
deploy:
  kubectl: {}
  kubeContext: docker-desktop
portForward:
  - resourceType: service
    resourceName: blockchain-dev
    port: 8545
