apiVersion: v1
kind: Service
metadata:
  name: blockchain-dev
  labels:
    component: blockchain-dev
    tier: blockchain-dev
spec:
  selector:
    component: blockchain-dev
    tier: backend
  ports:
    - port: 8545
      targetPort: 8545
