name: PR Merge (prod)

# on:
#   pull_request:
#     types: [edited]
#     branches: [prod]
#   issue_comment:
#     types: [created]
#   workflow_dispatch:
#     inputs:
#       source:
#         description: 'Input a trigger source'

on:
  push:
    branches: [main]
  repository_dispatch:
    types: [trigger-workflow]

env:
  WORKSPACE_ROOT: .
  ENVIRONMENT: prod

# Cancel redundant workflow runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # fast_forward_job:
  #   name: Fast Forward
  #   if: github.event_name == 'workflow_dispatch' || (github.event.issue.pull_request && contains(github.event.comment.body, '/ff'))
  #   runs-on: ubuntu-22.04
  #   steps:
  #     # To use this repository's private action, you must check out the repository
  #     - name: Checkout code into workspace directory
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #         persist-credentials: false
  #     # Basic use case example
  #     - name: Fast Forward PR
  #       if: ${{ github.event_name != 'workflow_dispatch' }}
  #       id: ff-action
  #       uses: samatechtw/fast-forward-js-action@master
  #       with:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         success_message: 'Success! Fast forwarded `prod` to `main` with ```git checkout prod && git merge main --ff-only```'
  #         failure_message: 'Failed! Cannot fast forward!'
  #         staging_branch: 'main'
  #         production_branch: 'prod'

  pre_job:
    # needs: fast_forward_job
    name: Run Workflow?
    runs-on: ubuntu-22.04
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'never'
          skip_after_successful_duplicate: 'true'
          # Changes to paths must be synced with pr-merge*.yml
          paths: '[".github/workflows/pr-commit.yml", "web/**", "backend/**", "*"]'
          paths_ignore: '["**/README.md", "skaffold*.yaml"]'

  repo-metadata:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    name: Get repo metadata
    runs-on: ubuntu-latest
    outputs:
      next_version: ${{ steps.meta.outputs.next_version }}
      sha8: ${{ steps.meta.outputs.sha8 }}
      repo_slug: ${{ steps.meta.outputs.repo_slug }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - id: meta
        uses: ./.github/actions/repo-metadata
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build-apps:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    name: Build Apps
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code into workspace directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/env-setup
      - name: Build web app
        run: npm run prod:web:build

  build-backend:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    name: Build Backend
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code into workspace directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          rustup set auto-self-update disable
          rustup toolchain install 1.80.1 --profile minimal
      - name: Build app in release mode
        run: cd backend && cargo build --release
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: backend-binaries
          path: |
            ./backend/target/release/db-app
            ./backend/target/release/crowdtrust-api
          if-no-files-found: error
          retention-days: 1

  build-docker-db-app-prod:
    needs: [pre_job, build-backend, repo-metadata]
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    name: DB API Production Image
    runs-on: ubuntu-22.04
    env:
      APP_NAME: db-app
      BRANCH_NAME: prod
    steps:
      - name: Checkout code into workspace directory
        uses: actions/checkout@v4
      - name: Download binary
        uses: actions/download-artifact@v4
        with:
          name: backend-binaries
          path: ./backend/target/release/${{env.APP_NAME}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Sanitize repo owner slug
        uses: actions/github-script@v6
        id: repo_slug
        with:
          result-encoding: string
          script: return `ghcr.io/${context.repo.owner.toLowerCase()}/${context.repo.repo.toLowerCase()}`
      - name: Build and push prod docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ${{env.WORKSPACE_ROOT}}
          push: true
          file: ${{env.WORKSPACE_ROOT}}/backend/${{env.APP_NAME}}/Dockerfile
          target: prod
          tags: |
            ${{needs.repo-metadata.outputs.repo_slug}}/${{env.ENVIRONMENT}}/${{env.APP_NAME}}:${{env.BRANCH_NAME}}-${{needs.repo-metadata.outputs.sha8}}-${{github.run_number}}
            ${{needs.repo-metadata.outputs.repo_slug}}/${{env.ENVIRONMENT}}/${{env.APP_NAME}}:latest

  build-docker-crowdtrust-api-prod:
    needs: [pre_job, build-backend, repo-metadata]
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    name: API Production Image
    runs-on: ubuntu-22.04
    env:
      APP_NAME: crowdtrust-api
      BRANCH_NAME: prod
    steps:
      - name: Checkout code into workspace directory
        uses: actions/checkout@v4
      - name: Download binary
        uses: actions/download-artifact@v4
        with:
          name: backend-binaries
          path: ./backend/target/release/${{env.APP_NAME}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Sanitize repo owner slug
        uses: actions/github-script@v6
        id: repo_slug
        with:
          result-encoding: string
          script: return `ghcr.io/${context.repo.owner.toLowerCase()}/${context.repo.repo.toLowerCase()}`
      - name: Build and push prod docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ${{env.WORKSPACE_ROOT}}
          build-args: |
            "S3_SECRET_ACCESS_KEY=${{ secrets.S3_SECRET_ACCESS_KEY_PROD }}"
            "SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY_PROD }}"
            "APP_AUTH_SECRET=${{ secrets.APP_AUTH_SECRET_PROD }}"
            "LAST_COMMIT_SHA=${{needs.repo-metadata.outputs.sha8}}"
            "RELEASE_VERSION=${{needs.repo-metadata.outputs.next_version}}"
          push: true
          file: ${{env.WORKSPACE_ROOT}}/backend/${{env.APP_NAME}}/Dockerfile
          target: prod
          tags: |
            ${{needs.repo-metadata.outputs.repo_slug}}/${{env.ENVIRONMENT}}/${{env.APP_NAME}}:${{env.BRANCH_NAME}}-${{needs.repo-metadata.outputs.sha8}}-${{github.run_number}}
            ${{needs.repo-metadata.outputs.repo_slug}}/${{env.ENVIRONMENT}}/${{env.APP_NAME}}:latest

  build-docker-web-prod:
    needs: [pre_job, repo-metadata]
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    name: Web Prod Image
    runs-on: ubuntu-22.04
    env:
      APP_NAME: web
      BRANCH_NAME: prod
    steps:
      - name: Checkout code into workspace directory
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build and push staging docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ${{env.WORKSPACE_ROOT}}
          build-args: |
            "LAST_COMMIT_SHA=${{needs.repo-metadata.outputs.sha8}}"
            "RELEASE_VERSION=${{needs.repo-metadata.outputs.next_version}}"
          push: true
          file: ${{env.WORKSPACE_ROOT}}/apps/${{env.APP_NAME}}/Dockerfile
          target: prod
          tags: |
            ${{needs.repo-metadata.outputs.repo_slug}}/${{env.ENVIRONMENT}}/${{env.APP_NAME}}:${{env.BRANCH_NAME}}-${{needs.repo-metadata.outputs.sha8}}-${{github.run_number}}
            ${{needs.repo-metadata.outputs.repo_slug}}/${{env.ENVIRONMENT}}/${{env.APP_NAME}}:latest

  build-docker-web-admin-prod:
    needs: [pre_job, repo-metadata]
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    name: Web Admin Prod Image
    runs-on: ubuntu-22.04
    env:
      APP_NAME: web-admin
      BRANCH_NAME: prod
    steps:
      - name: Checkout code into workspace directory
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Sanitize repo owner slug
        uses: actions/github-script@v6
        id: repo_slug
        with:
          result-encoding: string
          script: return `ghcr.io/${context.repo.owner.toLowerCase()}/${context.repo.repo.toLowerCase()}`
      - name: Build and push staging docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ${{env.WORKSPACE_ROOT}}
          build-args: |
            "LAST_COMMIT_SHA=${{needs.repo-metadata.outputs.sha8}}"
            "RELEASE_VERSION=${{needs.repo-metadata.outputs.next_version}}"
          push: true
          file: ${{env.WORKSPACE_ROOT}}/apps/${{env.APP_NAME}}/Dockerfile
          target: prod
          tags: |
            ${{needs.repo-metadata.outputs.repo_slug}}/${{env.ENVIRONMENT}}/${{env.APP_NAME}}:${{env.BRANCH_NAME}}-${{needs.repo-metadata.outputs.sha8}}-${{github.run_number}}
            ${{needs.repo-metadata.outputs.repo_slug}}/${{env.ENVIRONMENT}}/${{env.APP_NAME}}:latest

  release:
    needs:
      - build-docker-db-app-prod
      - build-docker-crowdtrust-api-prod
      - build-docker-web-prod
      - build-docker-web-admin-prod
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up NodeJS (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: |
          npm install -g semantic-release@23
          npm install -g @semantic-release/changelog@6
          npm install -g conventional-changelog-conventionalcommits@7
      - name: Release
        env:
          # Default GITHUB_TOKEN is OK as long as there no workflows triggered
          # on "create release" event as the latter will not be emitted.
          # See https://github.com/semantic-release/github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git branch -avv
          npx semantic-release --debug
